version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_vector_db
    command: "./qdrant --config-path app/config/config.yaml"
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
      - ./qdrant_config/config.yaml:app/config/config.yaml
    restart: always
    networks:
      - dialogflow-rag-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dialogflow_api
    ports:
      - "8008:8008"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - PYTHONUNBUFFERED=1
    volumes:
      - ../src:/app/src
      - ../config:/app/config
      - ../data:/app/data
      - ../helpers:/app/helpers
      - ../logs:/app/logs
    depends_on:
      - qdrant
    restart: always
    networks:
      - dialogflow-rag-network

volumes:
  qdrant_storage:

networks:
  dialogflow-rag-network:
    driver: bridge